#!/bin/bash
# -*- ENCODING: UTF-8 -*-
echo vorap13 | sudo --stdin chown -R vorap:vorap app database
echo vorap13 | sudo --stdin chmod -R 777 storage resources/js/components node_modules package-lock.json
